percona/pg_stat_monitor

README.md

Issue - (#3): README file update.
Modified the README for some corrections and better readability

Issue - (#3): README file update.

---

Makefile
README.md
pg_stat_monitor--1.0.sql
pg_stat_monitor.c

Issue - (#16): PG-112: Change the column name "ip" to "client_ip" for readability purpose.
Issue - (#17): PG-111: Show all the queries from complete and incomplete buckets.
Issue - (#18): PG-108: Log the bucket start time.
Issue - (#19): PG-99: Response time histogram.
Issue - (#20): PG-97: Log CPU time for a query.
Issue - (#21): PG-96: Show objects(tables) involved in the query.
Issue - (#22): PG-93: Retain the bucket, and don't delete the bucket automatically.
Issue - (#23): PG-91: Log queries of all the databases.
Issue - (#24): PG-116: Restrict the query size.
Issue - (#3) : README file update.

Major refactoring to support multiple new features.

---

percona-packaging/debian/control
percona-packaging/debian/control.in
percona-packaging/debian/rules
percona-packaging/rpm/pg-stat-monitor.spec
percona-packaging/scripts/pg_stat_monitor_builder.sh

Please **do not** merge without review

PG-119: Add version control

---

README.md

Updated install from rpm/deb packages section
Removed excessive TOC sections

PG-127-Readme updates for pg_stat_monitor

---

docs/RELEASE_NOTES.md

modified:   docs/RELEASE_NOTES.md

PG-157 Release notes for REL0_7_0_STABLE version

---

README.md

PG-198 Update readme with more attention to Percona Distribution

---

META.json
pg_stat_monitor.c
pg_stat_monitor.control

Bumping version for upcoming 0.9.2-beta1 release.

Bumping version for upcoming 0.9.2-beta1 release

---

CONTRIBUTING.md

PG-208 Doc Added Contibuting guide

---

META.json
README.md
docs/USER_GUIDE.md

Updated `README.md` and `USER_GUIDE.md`, improved wording and formatting. Slightly updated description in `META.json`.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>

Documentation: Minor textual/formatting improvements

---

README.md

PG-207 Readme updates

---

docs/USER_GUIDE.md

This PR is to update the documentation about views presentation inf the plugin.

PG-256: DOC about Views presentation

---

docs/COMPARISON.md
docs/REFERENCE.md
docs/USER_GUIDE.md

Moved pg_stat_monitor column description and compaison to separate docs
new file: REFERENCE.md
new file: COMPARISON.md

PG-215 User Guide updates

---

docs/USER_GUIDE.md

reorded usage examples to align with features' order

PG-215 Doc Fixed links to usage examples,

---

Makefile
hash_query.c
pg_stat_monitor--1.0.sql
pg_stat_monitor.c
pg_stat_monitor.h
pgsm_errors.c
pgsm_errors.h

Add support for PostgreSQL versions <= 13.

Pg 228 add errors view

---

pg_stat_monitor.c

There were couple issues to handle, the main one was that our log hook
(pgsm_emit_log_hook) was being called after the shared memory hook
completed (pgss_shmem_startup) but before PostgreSQL boostraping code
finished, thus triggering the following assertion during a call to
LWLockAcquire():
Assert(!(proc == NULL && IsUnderPostmaster));
proc is a pointer to MyProc, a PostgreSQL's shared global variable that
was not yet initalized by PostgreSQL.
We must also check for a NULL pointer return in pg_get_backend_status()
the pgstat_fetch_stat_local_beentry() function may return a NULL pointer
during initialization, in which case we use "127.0.0.1" for the client
address, and "postmaster" for application name.

PG-290: Fix crash when enabling debugging log level on PostgreSQL.

---

pg_stat_monitor--1.0.13.sql.in
pg_stat_monitor--1.0.14.sql.in
pg_stat_monitor.c

Updated sql files (pg_stat_monitor_settings view).
Using right variable name and level checking on pgss_store:
key.toplevel = ((exec_nested_level + plan_nested_level) == 0);

PG-299: Fix conflicts between devel and master.

---

README.md

PG-298 Add 'Report a bug' section to readme

---

Makefile
regression/expected/application_name_unique.out
regression/expected/error_insert.out
regression/expected/error_insert_1.out
regression/expected/histogram_1.out
regression/sql/application_name_unique.sql
regression/sql/error_insert.sql
regression/sql/histogram.sql

This commit adds following three (3) sql based test cases:
1) Test unique application name set by user.
2) Histogram function is working properly as desired.
3) Error on insert is shown with proper message.

PG-267 Add testcase to test histogram, unique application name and insert error.

---

README.md

PG-287 Added uninstall steps to README

---

.github/workflows/doc-build.yml

modified:   .github/workflows/doc-build.yml

PG-341 Updated GH action to build from main

---

api_check.sh

Added a new script that automates the process of checking API
compatibility between two pg_stat_monitor branches.

PG-342: Add API compatibility verification script.

---

guc.c

Added hook for checking histogram min and max values, in order to ensure
that histogram_min is always less than histogram_max.

PG-326: Validate histogram_min and histogram_max ranges.

---

guc.c
pg_stat_monitor--1.0.13.sql.in
pg_stat_monitor--1.0.14.sql.in
pg_stat_monitor--1.0.sql.in
pg_stat_monitor.c
pg_stat_monitor.h
regression/expected/guc.out
regression/expected/guc_1.out
regression/expected/histogram.out
regression/expected/histogram_1.out

PG-338: cherry-pick patch (b6838049b6a41e5d936aad920dd252f88e3ba774) by Diego
and I did some refactoring.

PG-338: Calls count is not correct in PG-13.

---

docs/USER_GUIDE.md

PG-359 Doc - Update pg_stat_monitor_settings view with new options

---

ADOPTERS.md

Added a basic `ADOPTERS.md` placeholder file for capturing user success stories.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>

PG-206: Add ADOPTERS.md file

---

docs/RELEASE_NOTES.md

modified:   docs/RELEASE_NOTES.md

PG-353 Release notes RC2

---

docs/USER_GUIDE.md

PG-359 Doc - Update pg_stat_monitor_settings view with new options (RC2)

---

docs/RELEASE_NOTES.md

modified:   docs/RELEASE_NOTES.md

PG-387 Release note for GA release

---

README.md

The README.md file was adapted to reflect the constant development of this branch and also to highlight that we also do have a stable branch. 

PG-405: Replace beta release warning in main branch

---

docs/overrides/404.html
mkdocs.yml

new file:   docs/overrides/404.html
modified:   mkdocs.yml

PG-407 Added a 404 page to docs

---

docs/USER_GUIDE.md

PG-411 Updated the list of primary keys

---

README.md

PG-413: added missing repository for PG v14

---

docs/index.md

PG-412: added 'Get engaged' to the welcome page

---

.github/workflows/coverage_test.yml
.github/workflows/postgresql-14-build.yml

PG-375: only run code coverage test on merge

---

docs/RELEASE_NOTES.md

PG-420: PGSM-1.0.1 release notes

---

.github/workflows/postgresql-14-package.yml

PG-416: added PostgreSQL14 package build workflow

---

.github/workflows/doc-build.yml

modified:   .github/workflows/doc-build.yml

PG-432 Fixed branch name of a  GH action

---

.github/workflows/postgresql-11-pmm.yaml
.github/workflows/postgresql-12-pmm.yaml
.github/workflows/postgresql-13-pmm.yaml
.github/workflows/postgresql-14-pmm.yaml

I had to close the previous PR due to some weird commit conflict

PMM-9951 Adding PGSM+PMM Integration tests

---

.github/workflows/postgresql-11-pmm.yaml
.github/workflows/postgresql-12-pmm.yaml
.github/workflows/postgresql-13-pmm.yaml
.github/workflows/postgresql-14-pmm.yaml

To make it easy for verification and branch build issues from forked and PMM tests

PMM-9951 moving integration tests to push

---

pg_stat_monitor.c

Fixing the issue introduced by 7efc3fa.

[PG-455] PGSM doesn't gather data for some pgsm_bucket_time settings

---

docs/USER_GUIDE.md

PG-459 Documented changes in setting pgsm sta

---

docs/USER_GUIDE.md

PG-460 Updated pgsm_normalized_query description

---

docs/USER_GUIDE.md

We had another two changes in our REL_1_STABLE branch, which need to be cherry-picked into our main branch. 
Signed-off-by: Kai Wagner [kai.wagner@percona.com](mailto:kai.wagner@percona.com)

Cherry-pick from REL_1_STABLE into main branch

---

t/0001_settings_pgsm_track_planning.pl
t/001_settings_default.pl
t/002_settings_pgsm_track_planning.pl
t/007_settings_pgsm_query_shared_buffer.pl
t/013_settings_pgsm_normalized_query.pl
t/017_execution_stats.pl
t/024_check_timings.pl
t/025_compare_pgss.pl
t/026_shared_blocks.pl
t/027_local_blocks.pl
t/028_temp_block.pl
t/expected/001_settings_default.out.12

This commit does not make any changes to the makefile. It simply ensures that
the test cases work with PG12. Necessary skip statements are added. Makefile
changes are to be done as part refactoring the Makefile.

PG-376: Enable TAP testing on PG 12

---

RELEASE_NOTES.md

PG-481 Release notes 1.1.0

---

RELEASE_NOTES.md

PG-517 Fixed the issue list formatting

---

META.json
RELEASE_NOTES.md
pg_stat_monitor.c
regression/expected/version.out

PG-526: bump version to 1.1.1 and adding release notes

---

pg_stat_monitor--1.0--2.0.sql
pg_stat_monitor--1.0.sql
pg_stat_monitor--2.0.sql
pg_stat_monitor.c
regression/expected/application_name.out
regression/expected/application_name_unique.out
regression/expected/basic.out
regression/expected/cmd_type.out
regression/expected/counters_1.out
regression/expected/database_1.out
regression/expected/error.out
regression/expected/error_insert.out
regression/expected/histogram_1.out
regression/expected/relations.out
regression/expected/rows.out
regression/expected/tags.out
regression/expected/top_query.out
t/expected/001_settings_default.out

PG-518: Drop the internal function permission from PUBLIC.
It will be a security problem to provide the internal function access to PUBLIC.
This commit will revoke all permission of internal functions from PUBLIC.

   PG-518: Drop the internal function permission from PUBLIC.

---

pg_stat_monitor--1.0--2.0.sql
pg_stat_monitor--1.0.sql
pg_stat_monitor--2.0.sql
pg_stat_monitor.c
regression/expected/application_name.out
regression/expected/application_name_unique.out
regression/expected/basic.out
regression/expected/cmd_type.out
regression/expected/counters_1.out
regression/expected/database_1.out
regression/expected/error.out
regression/expected/error_insert.out
regression/expected/histogram_1.out
regression/expected/relations.out
regression/expected/rows.out
regression/expected/tags.out
regression/expected/top_query.out
t/expected/001_settings_default.out

PG-306: The bucket start time should be timestamp instead of TEXT.

PG-306: The bucket start time should be timestamp instead of TEXT.

---

regression/expected/error_1.out
regression/expected/error_insert_1.out
regression/expected/top_query_1.out

Removed old files with same name and add these files to fix sql regression on PG 14 & 15.
1- regression/expected/error_1.out
2- regression/expected/error_insert_1.out
3- regression/expected/top_query_1.out

PG-554: Remove redundant files and fix regression.

---

pg_stat_monitor--1.0--2.0.sql
pg_stat_monitor--1.0.sql
pg_stat_monitor--2.0.sql
pg_stat_monitor.c
pg_stat_monitor.h

A new column is added to mention that bucket is active or done. there is     some timing based adjustment was required with that too.   

PG-310: Bucket is “Done” vs still being current/last.

---

hash_query.c
pg_stat_monitor.c
pg_stat_monitor.h

This patch does not work for  < PostgreSQL - 15. More work required.

 PG-488: Revert pg_stat_monitor: Overflow management.

---

regression/expected/functions.out

Due to removal pg_stat_monitor_settings view, functions sql test case was failing. Fixed that.

PG-354: Update expected output file for functions test case.

---

t/029_bucket_done.pl

Added a TAP test case to verify the behaviour of the new 'bucket_done' column.

PG-310: pg_stat_monitor: Bucket is Done vs still being current/last

---

hash_query.c
pg_stat_monitor.c
pg_stat_monitor.h

PG-585: pg_stat_monitor: Add code comments to the DSA related funcs..

---

t/024_check_timings.pl

1) Added the Group by caluse to make sure that bucket change doesn't have any
impact on aggregates of queries. 
2) Updated column names where required.
3) Updated pgbench parameters to reduce the time taken by test case, around
60-70% decrease in time taken by test case.

PG-573: Verify 024_check_timings.pl TAP test case.

---

t/025_compare_pgss.pl

1) Added the Group by clause to make sure that bucket change doesn't have any impact on aggregates of queries.
2) Updated column names where required.
3) Updated pgbench parameters to reduce the time taken by test case, around 70-80% decrease in time taken by test case.

PG-572: Verify 025_compare_pgss.pl TAP test case.

---

pg_stat_monitor.c

Resolved the issue with histogram outlier buckets. Also updated the printing of bucket ranges to be in correct set notation with reference to brackets. The lower bounds of buckets always have an exclusive range except for the first bucket, and the upper bounds always have an inclusive value.
( or ) => exclusive
{ or } => inclusive
The entire range is enclosed within the {} brackets.

PG-601: Histogram ranges are not correct

---

t/030_histogram.pl

Adding a tap test case for histogram feature where we are testing behaviour for different scenarios. 
1- Verify against default histogram values. 
2- Verify lower and upper range values, against user defined min and max. 
3- User defined histogram min, max and buckets. 
4- Negative values for min and max.

PG-559: Add a TAP testcase for historgram feature.

---

README.md
RELEASE_NOTES.md

Updated the README to include the PG15 support and also the copyright year was updated. 

PG-602: Updated the README and added PG15

---

pg_stat_monitor--2.0.sql
pg_stat_monitor.c

Saving the client IP address once per the lifetime of a backend. This avoid the expensive operation multiple times, and hence improving performance significantly.

PG-542: Performance improvement of pg_stat_monitor.

---

META.json
pg_stat_monitor.c
regression/expected/version.out

Version bumped for the 2.0.0 release.

PG-609: Bump version to 2.0.0 for the release.

---

guc.c
hash_query.c
pg_stat_monitor.c
pg_stat_monitor.h

Fixing code indentation with pgindent

---

RELEASE_NOTES.md
guc.c
hash_query.c
pg_stat_monitor.c
pg_stat_monitor.h

This is an issue raised by the PMM team. Hence, we've also updated the error functions to store pgsm_query_id for errors.

Multiple fixes including the addition of pgsm_query_id for errored out queries

---

pg_stat_monitor.c

The return value for snprintf was incorrectly recorded as plan length. That's been resolved.
As part of this fix, we've also eliminated the possibility of a potential memory leak when plan text was being saved.

PG-613: Postgresql crashes with Segmentation fault when query plan is enabled on large queries

---

META.json
pg_stat_monitor.c
regression/expected/version.out

Version bumped for the 2.0.1 release.

Version bumped for the 2.0.1 release.

---

META.json
hash_query.c
pg_stat_monitor.c
pg_stat_monitor.h
regression/expected/version.out
rpm/pg-stat-monitor.spec

REL_2_STABLE has four additional commits, and all are part of this PR.

Merging changes back to the main branch after the 2.0.1 release

---

RELEASE_NOTES.md

- Updating release notes for 2.0.1

Updating release notes for the 2.0.1 release.

---

Makefile
meson.build
pg_stat_monitor.c

* PG16 requires changes around one of the hooks, ifdef added
* Meson build file added

Postgres 16 support for PGSM

---

guc.c
pg_stat_monitor.c
regression/expected/relations_1.out
t/018_column_names.pl
t/026_shared_blocks.pl
t/027_local_blocks.pl
t/expected/007_settings_pgsm_query_shared_buffer.out.16

* Fixing issues with GUC initialization and function renames
* Fixed regression issues with PG16

PostgreSQL 16 support for PGSM

---

META.json
RELEASE_NOTES.md
pg_stat_monitor.c
regression/expected/version.out

Version bumped for the 2.0.2 release.

Version bumped for the 2.0.2 release.

---

META.json
RELEASE_NOTES.md
pg_stat_monitor.c
regression/expected/version.out

Version bumped for the 2.0.3 release.

Version bumped for the 2.0.3 release.

---

META.json
RELEASE_NOTES.md
pg_stat_monitor.c
regression/expected/version.out

Version bumped for the 2.0.4 release.

Version bumped for the 2.0.4 release

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature.yml

Issue templates similar to those that we have in PMM repo, check it: https://github.com/percona/pmm/issues/new/choose

[Proposal] Add issue templates

---

README.md

Add forum badge in readme

---

.github/workflows/postgresql-17-build.yml

https://www.postgresql.org/about/news/postgresql-164-158-1413-1316-1220-and-17-beta-3-released-2910/

Replace REL_17_BETA2 with REL_17_STABLE in CI

---

percona-packaging/scripts/pg_stat_monitor_builder.sh

Fixes llvm-devel package installation issue.

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

Add issue assingees

---

README.md

Add OSSF best practices badge

---

percona-packaging/scripts/pg_stat_monitor_builder.sh

Adds date timestamp to keep packages in different directories.

---

percona-packaging/scripts/pg_stat_monitor_builder.sh

Correctly get version from release branch

---

percona-packaging/scripts/pg_stat_monitor_builder.sh

PKG-922 fix rpm build on rhel10

PKG-922 fix rhel10 build

---

percona-packaging/scripts/pg_stat_monitor_builder.sh

[PKG-1038](https://perconadev.atlassian.net/browse/PKG-1038) remove outdated script from rpm builds
[PKG-1038]: https://perconadev.atlassian.net/browse/PKG-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix for rhel10 support
