pg_stat_monitor.c
What I did is when user set normalized_query to off, pg_stat_monitor will store a query with actual parameter as the query_text.
Here is simple example, assume we have table like following
```
test_stat_monitor=# \d employee
Table "public.employee"
Column |  Type   | Collation | Nullable | Default 
--------+---------+-----------+----------+---------
id     | integer |           |          | 
name   | text    |           |          | 
test_stat_monitor=# select * from employee;
id |  name  
----+--------
1 | kevin
2 | stuart
3 | bob
(3 rows)
```
And if we execute a parpared statement we will reuslt like this: 
```
test_stat_monitor=# select pg_stat_monitor_reset();
pg_stat_monitor_reset 
-----------------------
(1 row)
test_stat_monitor=# prepare getemp as select * from employee where id = …
```
=> PG-156: Adding a placeholder replacement function for prepared statement

pg_stat_monitor.c
Fixing message buffer overrun and incorrect index access to fix the server crash while running server regression.
Reviewed By: Ibrar Ahmad.
=> PG-169: Fixing Server Crash

pg_stat_monitor.c
If pg_stat_monitor is loaded after pg_stat_statement, then it will end
up calling standard_planner function twice in the pgss_planner_hook()
function, this will trigger an assertion failure from PostgreSQL as this
function expects an untouched Query* object, and the first call to
standard_planner() done by pg_stat_statements modifies the object.
To address the problem, we avoid calling standard_planner function twice
in pg_stat_monitor, if a previous handler is installed for the hook
planner_hook, then we assume that this previous hook has already called
standard_planner function and don't do it again.
=> PG-197: Fix conflict with pg_stat_statements

regression/expected/relations.out, regression/sql/relations.sql
Testcase 'relations' was failing due to absence of default locale setting 'c' in sql. Similarly due to changes in sql, expected output has to be changed.
=> DISTPG-271: Fix the failing 'relations' test case.

regression/expected/relations.out, regression/sql/relations.sql
Testcase 'relations' was failing due to absence of default locale setting 'c' in sql. Similarly due to changes in sql, expected output has to be changed.
=> DISTPG-271: Fix the failing 'relations' testcase on master branch. 

.github/workflows/coverage_test.yml, README.md
Added 'Coverall' (https://coveralls.io) code coverage to pg_stat_monitor repo so that in future we don't have to perform this activity manually. Secondly, it will also make sure that code coverage detailed report link and status is readily available on repos github main page for each checkin (PR & Push), eventually helping in development velocity.
=> PG-218: Added Coverall code coverage to pg_stat_monitor.

docs/USER_GUIDE.md, guc.c, regression/expected/guc.out, regression/expected/guc_1.out
Changed the default value of pgsm_bucket_time from 300 to 60. Now neither PMM users will need to adjust the default value, nor restart of PG server will be required for this purpose.
=> PG-195: Change pgsm_bucket_time value from 300 to 60.

hash_query.c, pg_stat_monitor--1.0.sql, pg_stat_monitor.c, pg_stat_monitor.h
Added a new view 'pg_stat_monitor_hook_stats' that provide execution
time statistics for all hooks installed by the module, following is a
description of the fields:
-       hook: The hook function name.
-   min_time: The fastest execution time recorded for the given hook.
-   max_time: The slowest execution time recorded for the given hook.
- total_time: Total execution time taken by all calls to the hook.
-   avg_time: Average execution time of a call to the hook.
-     ncalls: Total number of calls to the hook.
- load_comparison: A percentual of time taken by an individual hook
compared to every other hook.
To enable benchmark, code must be compiled with -DBENCHMARK flag, this
will make the hook functions to be replaced by a function with the same
name plus a '_benchmark' suffix, e.g. …
=> PG-222: Add benchmark support for measuring hook execution time.

pg_stat_monitor.c
The query_txt variable is allocated at the beginning of the
pg_stat_monitor_internal() function and released at the end, but an
extra malloc call to allocate it was added within an internal loop in
the funcion, thus allocating memory for every loop iteration, without
releasing the memory in the loop.
The query_txt variable can be reused inside the loop body, so this
commit removes the redundant declaration of query_txt from inside the
loop, which also fixes the leak.
=> PG-203: Fix memory leak.

pg_stat_monitor.c
pg_stat_monitor was not saving the pointer to the previous hook for
emit_log_hook, this commit fix the issue.
=> PG-204: Fix save previous emit_log_hook.

hash_query.c, pg_stat_monitor.c
The deadlock scenario is describe below:
1. pgss_store is called, it acquires the lock pgss->lock.
2. An error ocurr, mostly out of memory when accessing internal hash
tables used to store internal data, on functions
pgss_store_query_info and pgss_get_entry.
3. Call elog() to report out of memory error.
4. Our pgsm_emit_log_hook is called, it calls pgss_store_error, which in
turn calls pgss_store.
5. Try to acquire already acquired lock pgss->lock, deadlock happens.
To fix the problem, there are two modifications worth mentioning done by
this commit:
1. We are now passing HASH_ENTER_NULL flag to hash_search, instead of
HASH_ENTER, as read in postgresql sources, this prevents this
function from reporting error when out of memory, but instead it will
only return NULL if we pass …
=> PG-225: Fix deadlock in pgss_store.

.github/workflows/pg11test-pgdg-packages.yml, .github/workflows/pg12test-pgdg-packages.yml, .github/workflows/pg13test-pgdg-packages.yml, .github/workflows/pg14test-pgdg-packages.yml
Enable PGSM master branch regression/test with last Postgres release (actual
released packages) for supported server versions. This will make sure that we
would have already tested the PGSM compatibility well before PPG releases are done.
=> PG-227: Enable PGSM master branch regression/test with latest PG releases.

hash_query.c, pg_stat_monitor.c, pg_stat_monitor.h
A problem during bucket management was allowing some queries to be
duplicated, old entries would sit around without having their statistics
updated.
The problem would arise during the following chain of events:
1. A query goes through pgss_post_parse_analyze, in this stage (PGSS_PARSE)
we only save the query into the query buffer and create an entry in the
query hash table.
2. The query then goes through pgss_ExecutorStart (PGSS_EXEC), in this stage
we create an entry for query statistic counters with default values,
all time stats equal zero, etc.
3. The query then goes through pgss_ExecutorEnd (PGSS_FINISH), in this stage
we update the query statistis, no. calls, total time taken, min_time, etc.
The problem is that between steps 2 and 3, the current bucket ID timer may
have been …
=> PG-230: Fix duplicated query entries.

pg_stat_monitor.c
The loop that resets the query buffers was incorrecly using MAX_BUCKETS
to indicate the number of buckets to clear, which defaults to 10. If a
user lowers this value the loop would access a pointer beyond the number
of query buffers allocated.
Fix the problem by using the correct PGSM_MAX_BUCKETS GUC as the limit
to the loop.
=> PG-272: Fix server crash when calling pg_stat_monitor_reset().

regression/expected/guc_1.out
The guc_1.out is used for PG >= 13, where query track planning is
available, so it has been restored.
=> PG-276: Fix regression tests.

regression/expected/guc_1.out
Adjust guc_1.out to match guc.out defaults for pgsm_overflow_target.
=> PG-277: Fix regression tests (pgsm_overflow_target defaults).

pg_stat_monitor.c
If both modules are loaded then pg_stat_monitor detects that and avoid
calling standard_ProcessUtility() in ProcessUtility_hook hook, as
calling it twice is an error and triggers an assertion on PostgreSQL.
On PostgreSQL 13, pg_stat_monitor must be loaded after
pg_stat_statements, as pg_stat_statements doesn't do such verifications,
it end calling standard_ProcessUtility() and other functions even if
another module is registered, that is an error.
They fixed this problem with pg_stat_statements in PostgreSQL 14 and onward.
=> PG-234: Fix loading both pg_stat_monitor and pg_stat_statements.

README.md
Added a note about strict order of modules for PG 13 and earlier versions
modified:   README.md
=> PG-285 Doc: Order of modules

pg_stat_monitor.c
There were couple issues to handle, the main one was that our log hook
(pgsm_emit_log_hook) was being called after the shared memory hook
completed (pgss_shmem_startup) but before PostgreSQL boostraping code
finished, thus triggering the following assertion during a call to
LWLockAcquire():
Assert(!(proc == NULL && IsUnderPostmaster));
proc is a pointer to MyProc, a PostgreSQL's shared global variable that
was not yet initalized by PostgreSQL.
We must also check for a NULL pointer return in pg_get_backend_status()
the pgstat_fetch_stat_local_beentry() function may return a NULL pointer
during initialization, in which case we use "127.0.0.1" for the client
address, and "postmaster" for application name.
=> PG-290: Fix crash when enabling debugging log level on PostgreSQL.

pg_stat_monitor.c
If a backend would change the application name during execution,
pg_stat_monitor would then fail to read the updated value, as it caches
the result in order to avoid calling the expensive functions
pgstat_fetch_stat_numbackends() and pgstat_fetch_stat_local_beentry().
A workaround was found, we can just read an exported GUC from
PostgreSQL backend itself, namely application_name, from utils/guc.h,
thus saving us from having to call those expensive functions.
=> PG-296: Fix application name.

pg_stat_monitor.c
If a query exceeds pg_stat_monitor.pgsm_query_max_len, then it's
truncated before we save it into the query buffer (SaveQueryText).
When reading the query back, on pg_stat_monitor_internal, we allocate a
buffer for the query with length = pg_stat_monitor.pgsm_query_max_len,
the problem is that the read_query function adds a '\0' to the end of
the buffer when reading a query, thus if a query has been truncated, for
example, to 1024, when reading it back read_query will store the '\0' at
the position 1025, an out of array bounds position.
Then, when we call pfree to release the buffer, PostgreSQL notices the
buffer overrun and triggers an error assertion, the assertion calls our
error hook which attempts to acquire the shared pgss->lock before
pg_stat_monitor_internal has released it, …
=> PG-325: Fix deadlock.

pg_stat_monitor--1.0.13.sql.in, pg_stat_monitor--1.0.14.sql.in
After the split into multiple pg_stat_monitor--1.0.XX.sql.in sql files,
where XX is the PostgreSQL version, it was forgotten to add the errors
view to the relevant files, this commit fixes that.
=> PG-329: Fix creation of pg_stat_monitor_errors view on SQL files.

README.md
Added a link to pg_stat_monitor view reference in the Overview
Aded PG 14 to supported versions
Updated links in the Documentation section
modified:   README.md
=> PG-308 README Updates

CONTRIBUTING.md, README.md
Updated the Forum URL to point to the dedicated pg_stat_monitor forum in `README.md` and `CONTRIBUTING.md`, removed link to the Discord channel to ensure that conversations are focused to one location. Updated the table of contents in the README.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>
=> docs: Updated Forum URL, removed Discord link

pg_stat_monitor.c
Fixed a small typo introduced by commit
eaa9c08e24506529a317c20d419f33304c0d0918: PG-316: Convert blocks
timings to average per buckets.
The e->counters.sysinfo.utime = and e->counters.sysinfo.stime =
operations should be += to accumulate the results and calculate the
average correctly.
=> PG-311: Fix cpu_time and system_time accumulation.

t/023_missing_queries.pl
This test ensures that pg_stat_monitor moves only pending queries to the
next bucket when transitioning to a new one, also check that it keeps
the finished queries in the original bucket.
=> PG-345: Add tap test for missing queries.

pg_stat_monitor.c
Some queries were taking less than one millisecond to execute, since we
store cpu time values in milliseconds in a float, a value of 0.1 (a tenth
of millisecond) cast to int64 would truncate the fractional part and
the result would be zero.
To fix the problem, the cast to (int64) when calculating the average cpu
time was removed, when updating entry statistics in pgss_update_entry()
function.
=> PG-311: Fix user/system cpu time zero values.

api_check.sh
Added settings view to the api check script, both view interface (column
names and types) and values (SELECT * FROM pg_stat_monitor_settings)
were added for comparison between branches.
=> PG-351: Add pg_stat_monitor_settings api check.

Makefile
PG-352: pg_stat_monitor: make error when placed under contrib folder
Fixing issue where makefile was not honoring PG's global makefiles when placed under the contrib folder. This fix resolves it by setting MAJORVERSION from pg_config and then setting input SQL file version accordingly.
[PG-352](https://jira.percona.com/browse/PG-352)
=> Fixing issue where makefile was not honoring PG's global makefiles when placed under the contrib folder.

guc.c, hash_query.c, pg_stat_monitor--1.0.13.sql.in, pg_stat_monitor--1.0.14.sql.in, pg_stat_monitor.c, regression/expected/application_name_unique.out, regression/expected/counters.out, regression/expected/error_insert.out, regression/expected/error_insert_1.out, regression/expected/histogram.out, regression/sql/counters.sql
Following commits from the main branch were cherry-picked:
1. PG-338: Fix query call count (utilities). : 2c14e1dc0845ab173e74ed64edf3aa3352d2d614
2. PG-338: Fix counters regression test. : 52fb1fbc7dd5d0ebae8bd103f8bf78c5253225f7
3. PG-326: Validate histogram_min and histogram_max ranges.: 18b0c45ae06b7e49957311a0a864ecb466ab74dc
4. PG-350: Fix bucket time overflow.: 743bea6fdc27b88a83fda1de44ba7a0bd02dceb2
This led to a few compilation issues which were resolved. There are currently 2 regression failures which are most like expected output changes.
=> Cherry picking missing features/commits and resolving compilation issues

pg_stat_monitor.c
Collect accumulative value of sys_time and user_time, because
separate value for each same query will override the previous value.
=> PG-355: Collect accumulative value of sys_time and user_time.

pg_stat_monitor.c
Similar to pg_stat_statements, pg_stat_monitor tracks wal data metrics
since PostgreSQL 13, the problem was that for PostgreSQL versions 11 and
12 we left the WalUsage variable declared in the stack unitialized,
thus leading to garbage values.
Fixed the problem by ignoring the WalUsage variable value for PG <= 12.
=> PG-369: Fix wal_bytes values on PG <= 12.

README.md, docs/COMPARISON.md
Due to different data processing by both extensions, these stats appear as inconsistent.
modified:   README.md
modified:   docs/COMPARISON.md
=> PG-358 Documented block and WAL data display

README.md
Removed the beta comment from the README.me file as we've now reached 1.0.0 finally. 
=> PG-366 remove beta release warning from README.md

README.md
Updated the "Building from source" chapter. Added the postgresql-devel package for yum and postgresql-server-dev-all for apt variants and also removed the pg_config. 
=> PG-269: Updated install from source chapter

README.md
This will make sure that coverall.io stats are reflected as REL1_0_STABLE branch.
=> PG-384: Fix coverall.io badge on REL1_0_STABLE branch in PGSM repo.

README.md
This will make sure that coverall.io stats are reflected as main branch.
=> PG-383: Fix coverall.io badge on main branch in PGSM repo.

META.json
The META.json file had still an old release reference. Fixed that by changing it to "dev" for the main branch.
Added the "homepage" reference as requested in the PG-365 ticket.
=> PG-365:  change version in META.json file to dev

META.json
The META.json file had still an old release reference. Fixed that by changing it to the newest release. 
=> PG-365: bump version in META.json file to the latest release

guc.c, pg_stat_monitor.c
error: ‘for’ loop initial declarations are only allowed in C99 mode
=> PG-289 - Don't fail to build with C11 compilers

pg_stat_monitor.c
=> DISTPG-427: replaced return with goto exit to not break other extensions

.github/workflows/code-coverage-test.yml, .github/workflows/postgresql-14-build.yml
Right now the code coverage test runs on every push and pull-request. The problem is, that this always fails duo to the missing token within the source branch repository. As we don't need to test the code-coverage on every commit, we can streamline this and focus on the actual merge. Modified postgresql-14-build to keep the build test for every PR.
Signed-off-by: Kai Wagner [kai.wagner@percona.com](mailto:kai.wagner@percona.com)
=> PG-375: only run code coverage test on merge

pg_stat_monitor.c
There is some potential problem where there is a chance
that we got a duplicate queryid. This patch will eliminate
that problem.
=> PG-300: Fix potential duplicate queryid issue.

README.md
I've added the "How we work" section to our README.MD to explain our development model.
More detailed information on how to implement this model can also be found here: https://www.endoflineblog.com/implementing-oneflow-on-github-bitbucket-and-gitlab
=> PG-437: added the how we work section for OneFlow

pg_stat_monitor.c
Check for GUC (pgsm_extract_comments) was missing.
=> PG-449: Despite pgsm_extract_comments='no', comments are still visible.

ADOPTERS.md
Somehow my initial PR (https://github.com/percona/pg_stat_monitor/pull/196) got lost after some recent git branch reorganization.
Added a basic `ADOPTERS.md` placeholder file for capturing user success stories.
Signed-off-by: Lenz Grimmer <lenz.grimmer@percona.com>
=> PG-206: Add ADOPTERS.md file

.github/workflows/code-coverage-test.yml, .github/workflows/postgresql-11-build.yml, .github/workflows/postgresql-11-pgdg-package.yml, .github/workflows/postgresql-11-ppg-package.yml, .github/workflows/postgresql-12-build.yml, .github/workflows/postgresql-12-pgdg-package.yml, .github/workflows/postgresql-12-ppg-package.yml, .github/workflows/postgresql-13-build.yml, .github/workflows/postgresql-13-pgdg-package.yml, .github/workflows/postgresql-13-ppg-package.yml, .github/workflows/postgresql-14-build.yml, .github/workflows/postgresql-14-pgdg-package.yml, .github/workflows/postgresql-14-ppg-package.yml, .gitignore
1- Removed unsupported options from configure.
2- Reformatted files to break lines at 80 charachters.
3- Moved multiple 'apt install' and rm commands into a single one.
4- All workflows use and install llvm + clang version 11.
5- Updated workflows to ubuntu 22.04 where we are building PG server.
6- Added .vscode folder/files to .gitignore file.
=> PG-418: Cleanup workflows in github.

Makefile
The Makefile is refactored and unnecessary conditional statements are removed
in favor of handling version separately.
Also, the clean target is updated to remove generated files including results
folder and the ${DATA} file.
=> PG-352: pg_stat_monitor: make error when placed under contrib folder

.github/workflows/postgresql-12-build.yml, .github/workflows/postgresql-12-pgdg-package.yml, .github/workflows/postgresql-12-ppg-package.yml
Perl tap tests dependencies were missing, those are being installed now. Furthermore, workflow required some changes to enable logs to be available in case of tap tests failure(s).
=> PG-477: Install perl modules in PGSM-PG12 Build workflow.

pg_stat_monitor.c
Reverting the bucket locking mechanism to previous behavior. This has
a lot of room for improvement that needs to be part of a major refactoring
in the 2.x release.
=> PG-475: Inconsistent behaviour of PGSM

pg_stat_monitor.c
Ensuring the outer bound for the bucket is an exclusive boundary and it
as it belongs to the next bucket. To explain the point further, a set of
five second bucket would be:
Bucket 1: 00:00:00.00 -> 00:00:04.99...
Bucket 2: 00:00:00.05 -> 00:00:09.99...
Bucket 3: 00:00:00.10 -> 00:00:14.99...
...
=> PG-501: Missing Buckets and incorrect calls count.

pg_stat_monitor.c
PG 15 requires additional shared memory and LWLocks requests to be made from the newly introduced shmem_request_hook and disallows the requests initiated from outside the hook.
The commit makes moves the additional shared memory and LWLocks requests from _PG_init to shmem_request_hook for PG15
=> PG-520 pg_stat_monitor does not work with PG15

.github/workflows/postgresql-15-build.yml
=> PG-462: adding PG15 build to our workflows

pg_stat_monitor.c
pg_stat_monitor is a bit longer; therefore, it requires some code cleanup. Therefore I decided to turn these tasks into multiple commits and PR to avoid various changes in one PR. This will ease the review and Q/A process. In this commit, I have done these tasks.
1 - Fixing the compilation issue caused by the previous commit, where we removed the benchmarking code. It was causing problems for PostgreSQL-12.
=> PG-174: Code cleanup.

pg_stat_monitor--1.0--2.0.sql, pg_stat_monitor--2.0.sql, pg_stat_monitor.c, regression/expected/application_name.out, regression/expected/application_name_unique.out, regression/expected/basic.out, regression/expected/cmd_type.out, regression/expected/counters_1.out, regression/expected/database_1.out, regression/expected/error.out, regression/expected/error_insert.out, regression/expected/histogram_1.out, regression/expected/relations.out, regression/expected/rows.out, regression/expected/tags.out, regression/expected/top_query.out, t/expected/001_settings_default.out
The query status monitoring code was used to track the current query state, for example,      parsing, executing and finishing. After careful review, we have figured out that   it does not make sense while a lot of time same query is running. Therefore it   is also consuming resources. This commit will remove that feature. The upgrade SQL from 1.0 - 2.0 is also updated.
=> PG-320: Removing the query state code from the view.

pg_stat_monitor--1.0--2.0.sql, pg_stat_monitor--1.0.sql, pg_stat_monitor--2.0.sql, pg_stat_monitor.c, regression/expected/application_name.out, regression/expected/application_name_unique.out, regression/expected/basic.out, regression/expected/cmd_type.out, regression/expected/counters_1.out, regression/expected/database_1.out, regression/expected/error.out, regression/expected/error_insert.out, regression/expected/histogram_1.out, regression/expected/relations.out, regression/expected/rows.out, regression/expected/tags.out, regression/expected/top_query.out, t/expected/001_settings_default.out
PG-552: Remove unnecessary columns from PostgreSQL 11 and 12 views.
There was a typo while checking the PostgreSQL version in the SQL file. This commit
will fix the typo, and only the necessary columns will be visible in the view.
=> PG-552: Remove unnecessary columns from PostgreSQL 11 and 12 views.

pg_stat_monitor--1.0--2.0.sql, pg_stat_monitor--2.0.sql, pg_stat_monitor.c
Creating the infrastructure that'll allow using newer versions of the loadable module with old SQL declarations.
Also updating the build version to 2.0.0-dev
=> PG-555 :Infrastructure to allow multiple SQL APIs

pg_stat_monitor--1.0--2.0.sql, pg_stat_monitor--2.0.sql, pg_stat_monitor.c, pg_stat_monitor.h, t/018_column_names.pl
In line with pg_stat_statments for PG15, This commit adds eight new cumulative counters for jit operations, making it easier to diagnose how JIT is used in an installation. And two new columns, temp_blk_read_time, and temp_blk_write_time, respectively, show the time spent reading and writing temporary file blocks on disk.
Moreover, The commit also contains a few indentations and API adjustments.
=> PG-435: Adding new counters that are available in PG15

hash_query.c, pg_stat_monitor.c, pg_stat_monitor.h
Reimplement the storage mechanism of buckets and query texts using Dynamic shared memory. Since the dynamic shared memory can grow into a swap area, so we get the overflow out of the box.
oreover the new design saves the query pointer inside the bucket and eventually, the query text gets evicted with the bucket recycle.
Finally, the dynamic shared memory hash has a built-in locking mechanism so we can revisit the whole locking in pg_stat_monitor has potential for lots of performance improvements
=> PG-488: pg_stat_monitor: Overflow management.

pg_stat_monitor.c
This fix resolves the issue with incorrect query length in case of a normalized query when the query length exceeds PGSM_QUERY_MAX_LEN.
=> PG-576 - Segmentation fault caused by pg_stat_monitor unique queryid creation mechanism.

.github/workflows/postgresql-15-build.yml
As we are using compute_query_id on pg14 onwards for PGSM and it causes the server installcheck-world to fail (same behaviour with PGSS). To test installcheck-world on pg14 onwards we need to disable compute_query_id and run server installcheck-world. But for PGSM regression we will still have compute_query_id on.
=> PG-575: Enable installcheck-world on PG 14 & 15.

regression/expected/top_query.out, regression/expected/top_query_1.out
top_queryid test case was failing on all PG versions, pushing an update to expected output files.
=> PG-581: top_queryid expected output verification and change.

t/007_settings_pgsm_query_shared_buffer.pl, t/expected/007_settings_pgsm_query_shared_buffer.out, t/expected/007_settings_pgsm_query_shared_buffer.out.15
Verified and updated the 007_settings_pgsm_query_shared_buffer test case where it was failing due to bucket change on PG 12~15 intermittently, and also reduce the execution time.
=> PG-584: Verify and 007_settings_pgsm_query_shared_buffer.pl TAP test

pg_stat_monitor.c
Added the round off within the internal function so that values for blk_read_time, blk_write_time are rounded off to 4 decimal places.
Additionally, added rounding off for the PG15+ columns of temp_blk_read_time and temp_blk_write_time.
=> PG-582: blk_read_time and blk_write_time are not being rounded.

pg_stat_monitor--1.0--2.0.sql, pg_stat_monitor--2.0.sql, pg_stat_monitor.c, regression/expected/rows.out, regression/sql/rows.sql, t/005_settings_pgsm_enable_query_plan.pl, t/018_column_names.pl
The view now carries all the columns as pg_stat_statements. This required fixing data types of some of the columns, renaming a few, as well inclusion of new columns to make the view fully compatible with pg_stat_statements.
=> PG-543: pg_stat_monitor: PostgreSQL's pg_stat_statements compatible view.

guc.c, pg_stat_monitor--2.0.sql, pg_stat_monitor.c, pg_stat_monitor.h, t/009_settings_pgsm_histogram_max.pl, t/010_settings_pgsm_histogram_min.pl, t/expected/009_settings_pgsm_histogram_max.out, t/expected/010_settings_pgsm_histogram_min.out
Added buckets for queries that take less than minimum histogram time and one for the ones taking more than the max value specified.
Also, in case the buckets end up overlapping, on server start, an error will be thrown informing the user of this issue and requesting a rectification.
Refactored the code to consolidate the calculations in a single function.
=> PG-562: Histogram Ranges/Buckets are not correct.

pg_stat_monitor.c
There is no specific test case where I can either reproduce or validate the fix. Though, one of the suspects is this condition in pgss_store. Therefore removed, and it requires verification.
=> PG-588: Some queries are not being normalised.

t/026_shared_blocks.pl
1) Added the Group by clause to make sure that bucket change doesn't have any impact on aggregates of queries.
2) Updated column names where required.
3) Updated pgbench parameters to reduce the time taken by test case, around 70-80% decrease in time taken by test case.
=> PG-574: Verify 026_shared_blocks.pl TAP test case.

pg_stat_monitor.c
As an observability tool that serves data to other tools, data must be output without any loss. So rounding off causes data loss and rounding off errors when comparing different columns.
Therefore, it was decided to eliminate rounding off when outputting values. Any consumer of this data should round off data to whatever precision it prefers.
This behaviour is also consistent with pg_stat_statements.
=> PG-597: pg_stat_monitor: Remove rounding off for floating point values

pg_stat_monitor.c
Added the necessary capture of resource usage  in the process utility function. We are now storing CPU and user timings for a utility statement.
=> PG-586: pg_stat_monitor: CPU and user timing should be captured for utility statements as well

pg_stat_monitor.c
Resolving the compilation issue caused by ereport statement.
=> PG-599: PGSM build failure on PG-11

Makefile, hash_query.c, pg_stat_monitor--2.0.sql, pg_stat_monitor.c, pg_stat_monitor.h
This is the initial framework for locally maintaining hash entries so that we can insert the data in one go in the hash table being maintained in the shared memory.
Pending issues:
- This causes the regression to fail (and crash) from the counters test case
- The top query test case is failing,
- pgsm_store function is not saving all the data at the moment, especially the buffers, JIT and WAL information.
- The total time needs to be store separately for planning and execution.
=> Setting up framework for locally tracking the queries without using shared hash table

pg_stat_monitor--2.0.sql, pg_stat_monitor.c
Saving the client IP address once per the lifetime of a backend. This avoid the expensive operation multiple times, and hence improving performance significantly.
=> PG-542: Performance improvement of pg_stat_monitor.

guc.c, pg_stat_monitor.c, pg_stat_monitor.h, regression/expected/guc.out, regression/expected/guc_1.out, t/expected/001_settings_default.out, t/expected/001_settings_default.out.12, t/expected/009_settings_pgsm_histogram_max.out, t/expected/010_settings_pgsm_histogram_min.out, t/expected/011_settings_pgsm_bucket_time.out
Updated the GUC configuration and the relevant histogram functionality to track queries in lower cardinality than ms. This is done by saving the GUC values for histogram min and max values in real (double) type.
All test cases except for the 030 tap test are passing. The test case needs an update.
=> PG-607: Allow histogram to track queries in sub-ms time brackets

regression/expected/guc_2.out, t/030_histogram.pl
Due to enhancement in the histogram functionality to track queries in sub-ms time brackets, histogram TAP test case required changes to adapt to new behaviour. 
This PR also handles the failing SQL test case, GUC, on PG-11.
=> PG-608: pg_stat_monitor: Update histogram TAP testcase for sub-ms.

Makefile
This allows to override the `PG_CONFIG` variable through environment variables when wanting to use another one that is not in the `PATH`.
=> Make pg_config configurable in Makefile invocation

hash_query.c, pg_stat_monitor.c, pg_stat_monitor.h
It appears that this issue was being caused by improper handling of dynamic number of buckets. This commit resolves the issue.
Also, as part of a larger cleanup, memory context has been moved to local space from shared storage. Also, some unwanted and no-longer-needed variables are removed.
=> PG-624: pg_stat_monitor: Possible server crash when running pgbench with pg_stat_monitor loaded

.github/workflows/postgresql-16-build.yml, .github/workflows/postgresql-16-pgdg-package.yml
PGDG workflow will fail until packages are available for PG-16 on PGDG repo. But PG-16-Build will work.
=> Adding pg-16 build and PGDG workflows.

pg_stat_monitor.c
Do not look for the query in the hash if no query string is provided in the planner hook.
=> PG-645: pg_stat_monitor crashes PostgreSQL if there is citus ..

pg_stat_monitor.c
A potential lock contention could've been caused when an OOM warning was being emitted by the pgsm_store function. This could lead the pg_store_error function calling pgsm_store function and thereby trying to acquire and exclusive lock when a shared was already by the same process. This warning is now guarded by protection block.
=> PG-646: pg_stat_monitor hangs in pgsm_store

.github/workflows/code-coverage-test.yml, .github/workflows/postgresql-12-build.yml, .github/workflows/postgresql-12-pgdg-package.yml, .github/workflows/postgresql-12-ppg-package.yml, .github/workflows/postgresql-13-build.yml, .github/workflows/postgresql-13-pgdg-package.yml, .github/workflows/postgresql-13-ppg-package.yml, .github/workflows/postgresql-14-build.yml, .github/workflows/postgresql-14-pgdg-package.yml, .github/workflows/postgresql-14-ppg-package.yml, .github/workflows/postgresql-15-build.yml, .github/workflows/postgresql-15-pgdg-package.yml, .github/workflows/postgresql-15-ppg-package.yml, .github/workflows/postgresql-16-build.yml, .github/workflows/postgresql-16-pgdg-package.yml, .github/workflows/postgresql-16-ppg-package.yml
```
Warning: Cannot install IPC::RUN, don't know what it is.
Try the command
i /IPC::RUN/
to find objects with matching identifiers.
```
https://metacpan.org/pod/IPC::Run
Same for pg_tde: https://github.com/Percona-Lab/pg_tde/pull/156
=> Fix IPC::Run perl module name in CI

README.md
Updated README to reflect badge for pg-16 and content on the landing page.
=> Updated README to reflect badge for pg-16 and content on the landing page.

README.md
`pg_stat_monitor.pgsm_enable` parameter doesn't exist since `1.0.0-rc.2`
Commit where it was removed: https://github.com/percona/pg_stat_monitor/commit/153f8d2e875b53b86f1ae6c73886d2b7d2ad93fb
=> Remove redundant pgsm unistallation step from readme

README.md
=> Add instructions for Trunk, add PGXN badge

Makefile, pg_stat_monitor.c, regression/expected/denorm_prepared_statements.out, regression/expected/pgsm_query_id.out, regression/expected/pgsm_query_id_1.out, regression/expected/top_query.out, regression/expected/top_query_1.out, regression/sql/denorm_prepared_statements.sql, regression/sql/pgsm_query_id.sql
[PG-156](https://perconadev.atlassian.net/browse/PG-156)
Before this PR, `pg_stat_monitor` was unable to replace query placeholders when tracking prepared statements if `pg_stat_monitor.pgsm_normalized_query` is `off`.
With this update `pg_stat_monitor` now correctly store query argument values for prepared statements.
[PG-156]: https://perconadev.atlassian.net/browse/PG-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PG -156: replace query placeholders with actual arguments for prepared statements

pg_stat_monitor.c, pg_stat_monitor.h
Instead of trying to fix every case where we could throw an error and handling that properly we just make sure to disable the error capture of the hook while our backend holds the lock.
We keep the check for `IsSystemOOM()` in the hook even though that might not be relevant anymore because if we are in OOM it is not like there would be any point to log the error anyway.
This is done via a global variable, similar to the `__pgsm_do_not_capture_error` variable that we are replacing, which we also use in one place to disable recursive calls to the log hook where we do not hold the lock.
A potential future improvement would be to make this variable a counter, or have two separate globals, so that we could guard against recursive calls to the hook running us out of stack and not just prevent …
=> PG-1349 Prevent LWLock deadlocks from happening

Makefile, pg_stat_monitor--2.1--2.2.sql, regression/expected/decode_error_level.out, regression/expected/decode_error_level_1.out, regression/sql/decode_error_level.sql
Update decode_error_level function to support code up to PostgreSQL 17.
PG-1313
Fixes: https://github.com/percona/pg_stat_monitor/issues/506
This PR updated decode_error_level function with values up to PG17
Error code definitions can be found here: https://github.com/postgres/postgres/blob/REL_14_STABLE/src/include/utils/elog.h
=> PG-1313 Fix decode_error_level SQL function

pg_stat_monitor.c, t/034_update.pl
PG-1931
New fields were added in 2.1 version as they were introduced in PG17. However PGSM still can be installed with old API, so we have to return appropriate data set from C code to SQL.
=> PG-1931 Fix API compatibility

.github/workflows/postgresql-18-build.yml, .github/workflows/postgresql-18-pgdg-package.yml, Makefile, meson.build, pg_stat_monitor--2.2--2.3.sql, pg_stat_monitor.c, pg_stat_monitor.h, regression/expected/functions.out, regression/expected/functions_1.out, regression/expected/parallel.out, regression/expected/parallel_1.out, regression/expected/pgsm_query_id_2.out, regression/expected/squashing.out, regression/expected/squashing_1.out, regression/sql/parallel.sql, regression/sql/squashing.sql, t/018_column_names.pl, t/025_compare_pgss.pl, t/expected/007_settings_pgsm_query_shared_buffer.out.18
PG-1907
Full PG18 diff: https://github.com/postgres/postgres/compare/REL_17_STABLE...REL_18_STABLE
1. ExecutorRun signature change: https://github.com/postgres/postgres/commit/3eea7a0c97e94f9570af87317ce3f6a41eb62768
2. Use macro to define the number of enum values: https://github.com/postgres/postgres/commit/10b721821d6d6e27e594549cf105476dc28514c8
3. Use int64 instead of uint64 for queryIDs: https://github.com/postgres/postgres/commit/c3eda50b0648005281c2a3cf95375708f8ef97fc
In SQL we always show them as signed + it's just hashes, so we can do that change for all version of PG.
4. Add const list squashing during query normalization: 
https://github.com/postgres/postgres/commit/62d712ecfd940f60e68bde5b6972b6859937c412 
https://github.com/postgres/postgres/commit/0f65f3eec478db8ac4f217a608 …
=> PG-1907 PG-18 Support
